name: Build binaries and container images

on:
  push: # temp
  workflow_dispatch:
  schedule: [ cron: '0 4 * * *' ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    name: Build images
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/checkout@v4 
      - uses: actions/setup-go@v4
        with: { go-version: 1.22.2 }
      - run: go version
      - run: git clone https://codeberg.org/VnPower/PixivFE src
      - run: cd src && CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -mod=readonly -v -ldflags="-s -w" -o pixivfe && ./pixivfe --help