name: Build binaries and container images

on:
  push: # temp
  workflow_dispatch:
  schedule: [ cron: '0 4 * * *' ]

permissions:
  packages: write
  contents: read

jobs:
  build:
    name: Build images
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v4
        with: { go-version: 1.22.2 }
      - run: echo ${{ matrix.arch }}
      - run: go version